In [1]:
%matplotlib widget
import gudhi as gd
from gudhi import wasserstein
import persim
from persim import PersImage
from persim import *
from persim import wasserstein


import matplotlib.pyplot as plt
import numpy as np
from igraph import *
from scipy import sparse
import ripser
from numpy.random import default_rng

from scipy import special

In [2]:
rng = default_rng(0)
rng.random()

0.6369616873214543

In [3]:
def randomPD(card):
    pd = np.zeros((card,2))
    pd[:,0]=rng.random(card)
    pd[:,1]=pd[:,0] + rng.random(card)
    return pd

In [4]:
f, ax = plt.subplots(figsize=(8,8))
pd = randomPD(5)
ax.scatter(pd[:,0],pd[:,1])
ax.set_xlim((0,2))
ax.set_ylim((0,2))
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [5]:
sigma = {'sigma':[[0.05,0],[0,0.05]]}
pimgr = persim.PersistenceImager(pixel_size=0.01, birth_range=(0,1), kernel_params = sigma)
print(pimgr)


PersistenceImager(birth_range=(0.0, 1.0), pers_range=(0.0, 1.0), pixel_size=0.01, weight=persistence, weight_params={'n': 1.0}, kernel=gaussian, kernel_params={'sigma': [[0.05, 0], [0, 0.05]]})


In [6]:
f, ax = plt.subplots(figsize=(8,8))
pi = pimgr.transform(pd, skew = True)
pimgr.plot_image(pi, ax=ax)
plt.title("Persistence Image")
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:

Ws = []
PIds = []

pds = [randomPD(rng.integers(low=1, high=10)) for i in range(0,200)]


pimgr= persim.PersistenceImager(pixel_size=0.01, birth_range=(0,1), kernel_params = sigma)
pimgr.birth_range = (-1,2)
pimgr.pers_range = (0,2)
pis = pimgr.transform(pds, skew=True)
print(pimgr)

for i in range(0,100):
    for j in range(0,100):
        Ws.append(gd.wasserstein.wasserstein_distance(pds[i],pds[j+100],order=2, internal_p=np.inf)**2)
        PIds.append(np.linalg.norm(pis[i].flatten()-pis[j+100].flatten(),ord=2))

min(np.array(PIds)/np.array(Ws))

PersistenceImager(birth_range=(-1.0, 2.0), pers_range=(0.0, 2.0), pixel_size=0.01, weight=persistence, weight_params={'n': 1.0}, kernel=gaussian, kernel_params={'sigma': [[0.05, 0], [0, 0.05]]})


0.02231122827043619

In [17]:
f, ax = plt.subplots(figsize=(8,8))
ax.scatter(Ws, PIds)
x=np.linspace(0,1.5,100)
ax.plot(x,0.017*x, color='red')
#ax.set_ylim((0,5))
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
amin = np.argmin(np.array(PIds)/np.array(Ws))

X=pds[amin//100]
Y=pds[(amin%100)+100]

W=gd.wasserstein.wasserstein_distance(X,Y,order=2, internal_p=np.inf)**2
        
pi1 = pis[amin//100]
pi2 = pis[(amin%100)+100]
I=np.linalg.norm(pi1.flatten()-pi2.flatten(), ord=2)

f,((ax1,ax2),(ax3,ax4)) = plt.subplots(2,2,figsize=(8,8))
plt.title("$W_2^2=${}, $l_2$-distance between PIs = {}".format(W,I))

pimgr.plot_diagram(X, ax=ax1, skew=True)
pimgr.plot_diagram(Y, ax=ax2, skew=True)


pimgr.plot_image(pi1, ax = ax3)
pimgr.plot_image(pi2, ax = ax4)

plt.show()
print(I/W)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

0.02231122827043619


In [11]:
print(X)
print(Y)

[[0.52785844 0.93367999]
 [0.24840915 0.81703787]
 [0.63871822 1.16918948]
 [0.29572872 0.39790175]
 [0.44359375 1.30363428]
 [0.14139046 0.85526906]]
[[0.78677353 0.99704812]
 [0.22588341 0.61181677]
 [0.31652094 1.05723416]
 [0.25703363 1.03442957]
 [0.69273282 0.90558208]
 [0.78925949 1.48986639]
 [0.36327173 0.87300728]]


In [14]:
pixel_sizes = np.linspace(0.002,1,500)
dPIs = []
for ps in pixel_sizes:
    pimgr.pixel_size = ps
    pis = pimgr.transform([X,Y], skew = True)
    dPIs.append(np.linalg.norm(pis[0].flatten()-pis[1].flatten(),ord=2))

In [15]:
f, ax = plt.subplots(figsize=(8,8))
ax.scatter(pixel_sizes, dPIs)
x=np.linspace(0,0.2,100)
ax.plot(x,0.5*x, color='red')
#ax.set_ylim((0,5))
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [54]:
pimgr= persim.PersistenceImager(pixel_size=0.01, birth_range=(0,1), kernel_params = sigma)
pimgr.birth_range = (-1,2)
pimgr.pers_range = (0,2)

mins = np.zeros(21)
cardinalities = [100+20*t for t in range(0,21)]
for card in cardinalities:
    Ws = []
    PIds = []
    pds = [randomPD(card) for i in range(0,200)]


    pis = pimgr.transform(pds, skew=True)
    #print(pimgr)

    for i in range(0,100):
        for j in range(0,100):
            Ws.append(gd.wasserstein.wasserstein_distance(pds[i],pds[j+100],order=2, internal_p=np.inf)**2)
            PIds.append(np.linalg.norm(pis[i].flatten()-pis[j+100].flatten(),ord=2))

    mins[cardinalities.index(card)] = min(np.array(PIds)/np.array(Ws))

KeyboardInterrupt: 

In [ ]:
f, ax = plt.subplots(figsize=(8,8))
ax.scatter(np.linspace(100,500,21).astype(int), mins)
x=np.linspace(0,200,100)
ax.plot(x,0.0002*x, color='red')
#ax.set_ylim((0,5))
plt.show()

In [53]:
np.linspace(100,500,21).astype(int)

array([100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340,
       360, 380, 400, 420, 440, 460, 480, 500])